---
- name: Restart shairport-sync
  ansible.builtin.systemd:
    name: shairport-sync
    state: restarted
    daemon_reload: true

- name: Restart nqptp
  ansible.builtin.systemd:
    name: nqptp
    state: restarted
    daemon_reload: true

- name: Restart airplay-nowplaying
  ansible.builtin.systemd:
    name: airplay-nowplaying
    state: restarted
    daemon_reload: true

- name: Restart airplay-dashboard
  ansible.builtin.systemd:
    name: airplay-dashboard
    state: restarted
    daemon_reload: true

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
