# Inventory schema (informational, validated by converge with simple rules)
required:
  - fqdn
  - airplay_name
  - nic
optional:
  - alsa.vendor_id
  - alsa.product_id
  - alsa.serial
  - alsa.device_num
  - alsa.mixer
notes:
  fqdn: "Host FQDN under audio.home.arpa"
  nic: "Primary interface name (e.g., eno1)"
