---
# Optional ALSA overrides (used by bin/alsa-probe)
alsa:
  mixer: "PCM"         # optional
  device_num: 0         # optional (default 0)
  # vendor_id: "0x08bb" # optional (USB VID)
  # product_id: "0x2902"# optional (USB PID)
