name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ripgrep

      - name: No-sudo policy check
        run: |
          bash ./tests/no_sudo.sh

      - name: Smoke tests
        run: |
          bash ./tests/smoke.sh

