name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ripgrep

      - name: Lints
        run: |
          bash ./tools/lints.sh || true

      - name: Health (non-strict)
        run: |
          chmod +x ./bin/test-airplay2
          ./bin/test-airplay2 --no-strict || true
